---
name: Build docker images

"on":
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - .github/workflows/build-docker-images.yml
      - files/**
      - overlays/**
      - patches/**
      - release
      - release/**
      - scripts/*
      - src/**
      - templates/**
  pull_request:
    paths:
      - .github/workflows/build-docker-images.yml
      - files/**
      - overlays/**
      - patches/**
      - release
      - release/**
      - scripts/*
      - src/**
      - templates/**

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openstack_version:
          - victoria
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          pip3 install -r requirements.txt
          bash scripts/prepare.sh
          bash scripts/generate.sh
          bash scripts/patch.sh
          bash scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          OPENSTACK_VERSION: ${{ matrix.openstack_version }}
      - run: |
          bash scripts/tag.sh
          bash scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          OPENSTACK_VERSION: ${{ matrix.openstack_version }}
        if: github.ref == 'refs/heads/master'
